server:
  port: 9090

spring:
  zipkin:
    enable: true
    base-url: http://10.44.0.18:9411
    service:
      name: auth-service

  rabbitmq:
    host: 10.44.0.17
    port: 5672
    username: BilgeAdmin
    password: BilgeSifre
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.44.0.15:5432/FacebookAuthDB
    username: postgres
    password: BilgeAdminSifresi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



my-application:
  jwt:
    secret-key: "wr@M=dU4rur8splp0LvuPR_bEThutusT&q9ni3restaNlH-kOgab&wIFRobraspi"
    secret-key-env: ${SECRETKEY}
